### ISSUE TITLE
Example missing most common usecase for lists: Selecting an item

### ISSUE THREAD

**Issue by liminal** [googlesamples/android-RecyclerView#1]
The viewholder pattern is nice and helpful for performance and so on but my guess would be that in 99% of cases when we are using a RecyclerView (no matter what layoutmanager) what we want isn't just to display items but to be able to select an item.

And seeing as this seems to be the only sample of how to use RecyclerView:
Please add some sort of implementation of an item click handler to this sample.

**Comment by kroikie** [comment]
Items in a RecyclerView can be updated individually by calling notifyItemChanged(position) on the RecyclerView.Adapter.

**Comment by murraycu** [comment]
> Items in a RecyclerView can be updated individually by calling notifyItemChanged(position) on the RecyclerView.Adapter.

I don't see how that's at all relevant to this issue: "Example missing most common usecase for lists: Selecting an item". Maybe you closed the wrong issue by mistake?
